name: CompilarYEjecutar
# Define qué eventos disparan el workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-test:
    # El sistema operativo donde se ejecutará
    runs-on: ubuntu-latest
    steps:
      # 1. Descarga el código del repositorio
      - name: Checkout del código
        uses: actions/checkout@v6

      # 2. Configura el entorno (Java en este caso)
      - name: Configurar Java
        uses: actions/setup-node@v6
        with:
          java-version: '11'
          distribution: 'temurin'

      # 4. Compilar el proyecto
      - name: Compilar con Maven (Build)
        run: mvn clean compile

      # 5. Ejecutar las pruebas
      - name: Ejecutar tests
        run: mvn test

      - name: Build JAR
        run: mvn package
